#!/usr/bin/env ansible-playbook
# stdout_lines outputs the return of raw cmd in nice formatted lines
---
- hosts: ios 
  gather_facts: false
  connection: local
  serial: 12

  tasks:
#   - name: Disable ip domain lookup
#     ios_config:
#       lines: no ip domain lookup

   - name: Change interface description
     ios_config:
       lines:
         - description test interface
         - ip address 10.0.0.1 255.255.255.0
         - shut
       parents: interface Ethernet0/1

- hosts: nxos 
  gather_facts: false
  connection: local

  tasks:
   - name: Disable ip domain lookup
     ios_config:
       lines: ip domain-lookup

- hosts: xrv
  gather_facts: false
  connection: local

  tasks:
   - name: Disable ip domain lookup
     ios_config:
       lines: domain lookup disable 


#   - name: Configure OSFP 100 and put all interfaces into Area 0 
#     ios_config:
#       lines: 
#         - network 10.30.30.0 0.0.0.255 area 1
#       parents: router ospf 1

#   - name: configure Gig2 settings
#     ios_config:
#       lines:
#         - description test interface
#         - ip address 10.0.0.1 255.255.255.0 
#         - shut
#       parents: "interface Ethernet 1/2"


#   - name: configure NTP Server
#     ios_config:
#       lines:
#         - ntp server 125.56.55.53  



- hosts: ios
  gather_facts: false
  connection: local
  serial: 12

  tasks:
   - name: SAVE CONFIG
     ios_command:
       commands:
         - write memory

- hosts: xrv
  gather_facts: false
  connection: local

  tasks:
   - name: SAVE CONFIG
     ios_config:
       lines:
         - commit 

- hosts: nxos 
  gather_facts: false
  connection: local

  tasks:
   - name: SAVE CONFIG
     ios_command:
       commands:
         - copy running-config startup-config 

#   - name: SAVE CONFIG 
#     ios_command:
#       commands:
#         - write memory



