all:
 hosts: 
   r1:   { ansible_host: 172.16.192.1 }
   r2:   { ansible_host: 172.16.192.2 }
   r3:   { ansible_host: 172.16.192.3 }
   r4:   { ansible_host: 172.16.192.4 }
   r5:   { ansible_host: 172.16.192.5 }
   r6:   { ansible_host: 172.16.192.6 }
  vars
    ansible_user: cisco
    ansible_ssh_pass: cisco
    ansible_os: ios


