#!/usr/bin/env ansible-playbook
#the vars shows everything ansibla knows about the host
- name: Execute show version on IOS
  hosts: ios
  gather_facts: no 
  tasks:
  - raw: "show ip int brief"
    register: show
  - debug: var=vars
  hosts: nxos
  tasks:
  - raw: "show ip int brief"
    register: show
  - debug: var=vars

