#!/usr/bin/env ansible-playbook
# stdout_lines outputs the return of raw cmd in nice formatted lines
- name: Execute show version on IOS
  hosts: ios 
  gather_facts: no 
  tasks:
  - raw: "show ip int brief"
    register: show
  - debug: var=show.stdout_lines

